[package]
name = "did-web"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "DIDkit SSI DIDWeb"
keywords = ["did", "ssi", "did:web"]
repository = "https://github.com/kobakaku/didkit/ssi/ssi-dids"

[dependencies]
ssi-dids = { path = "../ssi-dids", version = "0.1" }
serde_json = "1.0"